### ISSUE TITLE
计算机网络第三章学习笔记 | Hollin的代码之路

### ISSUE THREAD

**Issue by Hooollin** [Hooollin/hooollin.github.io#7]
https://hooollin.github.io/2020/01/31/computer-networking-chapter3/ 

 运输层 运输层位于应用层和网络层之间，是分层网络体系结构中的重要部分。 概述和运输层服务 运输层协议为运行在不同主机上的应用进程之间提供了逻辑通信（logic communication）。简而言之就是两台主机之间好像是直接相连的。应用进程使用运输层提供的逻辑通信互相发送报文，不许考虑承载这些报文的物理设备。 实际上运输层的协议是在端系统中实现的而不是在路由器中实现的（我的确认为是在路由器里面实现

**Comment by hqweay** [comment]
屌，记录得好仔细。🥳
PS：评论好像有点问题。

**Comment by Hooollin** [comment]
> @hqweay
> 屌，记录得好仔细。🥳
> PS：评论好像有点问题。

这该死的研究生竟然如此难考...
bug找到了，这下应该好了
